# Generated by Django 2.0.3 on 2018-03-19 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_date', models.DateTimeField(verbose_name='Date booked')),
                ('booking_ref', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('party_size', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=80)),
                ('user_idcd', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='user_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.User'),
        ),
    ]
